- hosts: reddit_bot_server
  gather_facts: yes
  tasks:
#    - name: debug lookup("env", "PWD")
#      debug:
#        var: lookup("env", "PWD")
#
#    - name: debug ansible_env.PWD
#      debug:
#        var: ansible_env.PWD

    - name: debug ansible_env
      debug:
        var: ansible_env

    - name: Create a cloud function
      local_action:
        module: google.cloud.gcp_cloudfunctions_cloud_function
        name: poverty_reddit_bot
        location: asia-northeast1
        entry_point: helloGET
        source_archive_url: gs://ansible-cloudfunctions-bucket/function.zip
        trigger_http: 'false'
        project: '{{ lookup("env", "GCP_PROJECT_ID") }}'
        auth_kind: serviceaccount
        service_account_file: '{{ lookup("env", "GCP_SERVICE_ACCOUNT_FILE") }}'
        state: present

